#!/usr/bin/env bash
# install-cwt-cli.sh — one-time installer for the global `cwt` command.
#
# Writes ~/.cwt-cli.sh that bootstraps CWT_TEMPLATE_DIR and sources
# $CWT_TEMPLATE_DIR/.cwt/cli.sh. Appends 'source ~/.cwt-cli.sh' to the
# user's shell rc file if not already present.
#
# Idempotent — re-running updates paths, leaves shell config alone if
# already installed.
#
# Usage:
#   make cwt-install          (interactive)
#   make cwt-install YES=1    (non-interactive, auto-confirm)
set -uo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
DIM='\033[2m'
BOLD='\033[1m'
NC='\033[0m'

AUTO_YES="${1:-}"

TEMPLATE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BOOTSTRAP="$HOME/.cwt-cli.sh"

# ── sanity: are we actually in a CWT template? ──
if [ ! -d "$TEMPLATE_DIR/.cwt" ] || [ ! -f "$TEMPLATE_DIR/.cwt/cli.sh" ]; then
  echo -e "${RED}Error:${NC} this doesn't look like a CWT template."
  echo "  Expected: $TEMPLATE_DIR/.cwt/cli.sh"
  exit 1
fi

# ── detect shell + rc file ──
USER_SHELL="$(basename "${SHELL:-/bin/bash}")"
case "$USER_SHELL" in
  zsh)  RC_FILE="$HOME/.zshrc" ;;
  bash)
    if [ -f "$HOME/.bashrc" ]; then RC_FILE="$HOME/.bashrc"
    elif [ -f "$HOME/.bash_profile" ]; then RC_FILE="$HOME/.bash_profile"
    else RC_FILE="$HOME/.bashrc"; fi
    ;;
  fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
  *)    RC_FILE="$HOME/.profile" ;;
esac

echo ""
echo -e "${BOLD}CWT CLI — global install${NC}"
echo "========================="
echo ""
echo "  Template: $TEMPLATE_DIR"
echo "  Shell:    $USER_SHELL"
echo "  RC file:  $RC_FILE"
echo "  Bootstrap: $BOOTSTRAP"
echo ""

# ── prompt ──
if [ "$AUTO_YES" != "--yes" ] && [ "$AUTO_YES" != "-y" ]; then
  echo -e "This will:"
  echo -e "  1. Write ${BOLD}$BOOTSTRAP${NC} (sets CWT_TEMPLATE_DIR, sources cli.sh)"
  echo -e "  2. Add ${BOLD}'source $BOOTSTRAP'${NC} to $RC_FILE (if not already there)"
  echo ""
  echo -e "  After install, ${BOLD}cwt init <name>${NC} works from any directory."
  echo ""
  read -rp "  Proceed? [Y/n]: " CONFIRM
  if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
    echo "  Aborted."
    exit 0
  fi
fi

# ── write bootstrap ──
cat > "$BOOTSTRAP" <<EOF
# ~/.cwt-cli.sh — CWT CLI bootstrap (generated by install-cwt-cli.sh)
# Managed file. Re-run 'make cwt-install' in the template to regenerate.
export CWT_TEMPLATE_DIR="$TEMPLATE_DIR"
if [ -f "\$CWT_TEMPLATE_DIR/.cwt/cli.sh" ]; then
  # shellcheck disable=SC1091
  source "\$CWT_TEMPLATE_DIR/.cwt/cli.sh"
fi
EOF
echo -e "  ${GREEN}wrote${NC} $BOOTSTRAP"

# ── ensure rc file sources bootstrap ──
SOURCE_LINE="[ -f \"\$HOME/.cwt-cli.sh\" ] && source \"\$HOME/.cwt-cli.sh\""
mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"

if grep -F ".cwt-cli.sh" "$RC_FILE" >/dev/null 2>&1; then
  echo -e "  ${DIM}already sourced from $RC_FILE${NC}"
else
  {
    echo ""
    echo "# CWT CLI — added by install-cwt-cli.sh"
    echo "$SOURCE_LINE"
  } >> "$RC_FILE"
  echo -e "  ${GREEN}appended source line to${NC} $RC_FILE"
fi

# ── done ──
echo ""
echo -e "${GREEN}✓ installed${NC}"
echo ""
echo "  Next: open a new terminal OR run:"
echo -e "    ${BOLD}source $RC_FILE${NC}"
echo ""
echo "  Then verify:"
echo -e "    ${BOLD}cwt help${NC}"
echo "    cwt init my-first-app"
echo ""
