#!/usr/bin/env bash
# install-cwt-cli.sh — one-time installer for the global `cwt` command.
#
# Writes ~/.cwt-cli.sh that bootstraps CWT_TEMPLATE_DIR and sources
# $CWT_TEMPLATE_DIR/.cwt/cli.sh. Appends 'source ~/.cwt-cli.sh' to the
# user's shell rc file if not already present.
#
# Idempotent — re-running updates paths, leaves shell config alone if
# already installed.
#
# Usage:
#   make cwt-install          (interactive)
#   make cwt-install YES=1    (non-interactive, auto-confirm)
set -uo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
DIM='\033[2m'
BOLD='\033[1m'
NC='\033[0m'

AUTO_YES="${1:-}"

TEMPLATE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BOOTSTRAP="$HOME/.cwt-cli.sh"

# ── sanity: are we actually in a CWT template? ──
if [ ! -d "$TEMPLATE_DIR/.cwt" ] || [ ! -f "$TEMPLATE_DIR/.cwt/cli.sh" ]; then
  echo -e "${RED}Error:${NC} this doesn't look like a CWT template."
  echo "  Expected: $TEMPLATE_DIR/.cwt/cli.sh"
  exit 1
fi

# ── detect shell + rc file ──
USER_SHELL="$(basename "${SHELL:-/bin/bash}")"
case "$USER_SHELL" in
  zsh)  RC_FILE="$HOME/.zshrc" ;;
  bash)
    if [ -f "$HOME/.bashrc" ]; then RC_FILE="$HOME/.bashrc"
    elif [ -f "$HOME/.bash_profile" ]; then RC_FILE="$HOME/.bash_profile"
    else RC_FILE="$HOME/.bashrc"; fi
    ;;
  fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
  *)    RC_FILE="$HOME/.profile" ;;
esac

echo ""
echo -e "${BOLD}Setting up the \`cwt\` shortcut${NC}"
echo "================================"
echo ""
echo -e "  ${DIM}This lets you type ${BOLD}\`cwt init my-app\`${NC}${DIM} from any folder${NC}"
echo -e "  ${DIM}instead of having to cd into the template every time.${NC}"
echo ""
echo "  Template folder:  $TEMPLATE_DIR"
echo "  Your shell:       $USER_SHELL"
echo "  Shell settings:   $RC_FILE"
echo ""

# ── prompt ──
if [ "$AUTO_YES" != "--yes" ] && [ "$AUTO_YES" != "-y" ]; then
  echo -e "${BOLD}What this does:${NC}"
  echo -e "  1. Creates a tiny helper file: $BOOTSTRAP"
  echo -e "  2. Adds ${BOLD}one line${NC} to $RC_FILE so your shell knows about it"
  echo ""
  echo -e "  ${DIM}(That's the only change. Delete the helper file + that line to undo.)${NC}"
  echo ""
  read -rp "  OK to proceed? [Y/n]: " CONFIRM
  if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
    echo "  No changes made."
    exit 0
  fi
fi

# ── write bootstrap ──
cat > "$BOOTSTRAP" <<EOF
# ~/.cwt-cli.sh — CWT CLI bootstrap (generated by install-cwt-cli.sh)
# Managed file. Re-run 'make cwt-install' in the template to regenerate.
export CWT_TEMPLATE_DIR="$TEMPLATE_DIR"
if [ -f "\$CWT_TEMPLATE_DIR/.cwt/cli.sh" ]; then
  # shellcheck disable=SC1091
  source "\$CWT_TEMPLATE_DIR/.cwt/cli.sh"
fi
EOF
echo -e "  ${GREEN}✓${NC} created helper file: $BOOTSTRAP"

# ── ensure rc file sources bootstrap ──
SOURCE_LINE="[ -f \"\$HOME/.cwt-cli.sh\" ] && source \"\$HOME/.cwt-cli.sh\""
mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"

if grep -F ".cwt-cli.sh" "$RC_FILE" >/dev/null 2>&1; then
  echo -e "  ${DIM}✓ $RC_FILE already loads it — nothing to add${NC}"
else
  {
    echo ""
    echo "# CWT shortcut — added by install-cwt-cli.sh"
    echo "$SOURCE_LINE"
  } >> "$RC_FILE"
  echo -e "  ${GREEN}✓${NC} added one line to: $RC_FILE"
fi

# ── done ──
echo ""
echo -e "${GREEN}${BOLD}All set!${NC}"
echo ""
echo "  To start using it right now, pick one:"
echo -e "    A) open a new terminal window, OR"
echo -e "    B) run this in the current terminal: ${BOLD}source $RC_FILE${NC}"
echo -e "       ${DIM}(that reloads your shell settings so \`cwt\` works)${NC}"
echo ""
echo "  Then try:"
echo -e "    ${BOLD}cwt help${NC}           ${DIM}— see what \`cwt\` can do${NC}"
echo -e "    ${BOLD}cwt init my-app${NC}    ${DIM}— scaffold a new project${NC}"
echo ""
